#!/usr/bin/env bash

# Fronde : lance les notifications Github au démon de notification
# Utilise notify-send
# ATTENTION : il faut une clé API. Cf. https://github.com/settings/tokens

# Utilisation : 
#    API_KEY=5b10dbc8f77a19f3d8c5a2f0fdaa ./fronde

priority="normal" # low, normal, critical
time="5000" # expiry time in milliseconds
api_url="https://api.github.com/notifications"

# Avons besoin d'une clé API Github
if [[ -z "$API_KEY" ]]; then
	echo "Clé API manquante ! Renseignez API_KEY." && exit 1
fi

echo "Recherche des notifications…"
text=`curl -s -u blankoworld:${API_KEY} "${api_url}"`
echo "${text}" |jq -c '.[] | {
  name: .repository.full_name,
  tag: .subject.type,
  description: .subject.title}'| while read json
do
  depot=$(echo $json|jq -r .name)
  tag=$(echo $json|jq -r .tag)
  detail=$(echo $json|jq -r .description)
  notify-send -u $priority -t $time "$depot" "$tag : $detail"
done

echo "…terminé"

exit 0
